<a href="https://colab.research.google.com/github/DennisKoech115325/AI-Group_Assignment/blob/main/AI_Group_Task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [923]:
import pandas as pd #datat set library
import numpy as np #linear algebra library

In [924]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform,normal

Hyperparameters

In [925]:
batch_size = 2
learning_rate = uniform(0,1)
learning_rate

0.25813488703882026

In [926]:
data_dict={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
           'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [927]:
data = pd.DataFrame(data_dict)

In [928]:
data

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [929]:
X = data.drop('Target',axis=1)
Y = data['Target']

In [930]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [931]:
np.reshape(array(Y),(-1,1))

array([[20],
       [15],
       [60],
       [70],
       [50],
       [40]])

In [932]:
X_trans = Normalizer(norm='max').fit_transform(X)

In [933]:
Y_trans = Normalizer(norm='max').fit_transform(np.reshape(array(Y),(1,-1)))

In [934]:
X_trans

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [935]:
Y_trans

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN MODEL FROM MAX

In [936]:
weight_1 = uniform(-1,1,(3,2))
weight_1

array([[ 0.92054611,  0.39178613],
       [ 0.8837553 , -0.52314193],
       [ 0.45322034, -0.73180173]])

In [937]:
weight_2 = uniform(-1,1,(2,1))
weight_2

array([[-0.98823118],
       [ 0.12098553]])

In [938]:
ANN_function()

3.1256142890528014

In [939]:
for i in range(100):
  x = ANN_function()
  """weight_1 = delta_weight1(x,weight_1)
  weight_2 = delta_weight2(x,weight_2)"""

In [940]:
def ANN_function():
  sum_mse = 0
  i = 0
  y = i
  for i in range(0,3):
    output_1 = X_trans[y:batch_size+y]@weight_1
    act_out1 = sigmoid(output_1).numpy()
    final_out = act_out1@weight_2
    true_y = Y_trans[0][0:batch_size]
    pred_y = final_out.T[0]
    x = mse(true_y,pred_y).numpy()
    y += 2
    sum_mse += x
  return sum_mse

In [941]:
def delta_weight1(fmse, cur_w1 = []):
  cur_w1 = cur_w1 + (cur_w1 * learning_rate * fmse)
  return cur_w1

In [942]:
def delta_weight2(fmse, cur_w2 = []):
  cur_w2 = cur_w2 + (learning_rate * fmse * cur_w2)
  return cur_w2

Below isnt necessary

In [943]:
X_trans[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [944]:
output_1 = X_trans[0:batch_size]@weight_1
output_1

array([[ 1.71255225, -0.9152436 ],
       [ 1.80148033, -0.50243372]])

In [945]:
act_out1 = sigmoid(output_1).numpy()
act_out1

array([[0.84716703, 0.28592803],
       [0.85832904, 0.37696891]])

In [946]:
final_out = act_out1@weight_2
final_out

array([[-0.80260372],
       [-0.80261974]])

Above is done with forward propagation

Compute MSE

In [947]:
true_y = Y_trans[0][0:batch_size]
pred_y = final_out.T[0]

In [948]:
mse(true_y,pred_y).numpy()

1.1092663925997333